# Scaffolding generated by Casein v.3.1.7

module Casein
  class DashboardController < Casein::CaseinController
    layout 'constellation'
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
    respond_to :html,:js,:xml

    def index
    end

  

end
end