# Scaffolding generated by Casein v.3.1.7

module Casein
  class GalleryTypesController < Casein::CaseinController
      layout 'constellation'
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Gallery types'
  		@gallery_types = GalleryType.paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View gallery type'
      @gallery_type = GalleryType.find params[:id]
    end
 
    def new
      @casein_page_title = 'Add a new gallery type'
    	@gallery_type = GalleryType.new
    end

    def create
      @gallery_type = GalleryType.new params[:gallery_type]
    
      if @gallery_type.save
        flash[:notice] = 'Gallery type created'
        redirect_to casein_gallery_types_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new gallery type'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update gallery type'
      
      @gallery_type = GalleryType.find params[:id]
    
      if @gallery_type.update_attributes params[:gallery_type]
        flash[:notice] = 'Gallery type has been updated'
        redirect_to casein_gallery_types_path
      else
        flash.now[:warning] = 'There were problems when trying to update this gallery type'
        render :action => :show
      end
    end
 
    def destroy
      @gallery_type = GalleryType.find params[:id]

      @gallery_type.destroy
      flash[:notice] = 'Gallery type has been deleted'
      redirect_to casein_gallery_types_path
    end
  
  end
end