# Scaffolding generated by Casein v.3.1.7

module Casein
  class LocationsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
    layout 'constellation'    
    respond_to :html,:js,:xml
    helper_method :sort_column, :sort_direction
  
  
  
  
    def index
      per_page=params[:per_page]||=10
  		@locations = Location.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page =>per_page, :page => params[:page])
  		respond_with(@locations)
    end


    
    
  
    def show
      
      @location = Location.find params[:id]
    end
 
    def new
      
    	@location = Location.new
    end

    def create
      @location = Location.new params[:location]
    
      if @location.save
        flash[:notice] = 'Location created'
        redirect_to casein_locations_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new location'
        render :action => :new
      end
    end
  
    def update
      
      
      @location = Location.find params[:id]
    
      if @location.update_attributes params[:location]
        flash[:notice] = 'Location has been updated'
        redirect_to casein_locations_path
      else
        flash.now[:warning] = 'There were problems when trying to update this location'
        render :action => :show
      end
    end
 
    def destroy
      @location = Location.find params[:id]

      @location.destroy
      flash[:notice] = 'Location has been deleted'
      redirect_to casein_locations_path
    end
    
    
      def enabledisable
        @location = Location.find params[:id]
        enbl=params[:enabled]

        if @location.update_attribute(:enabled,enbl )
          if enbl
            message = "@location published, it is visible now"          
          else
            message = "@location un-published, it is hidden now"
          end
        else
          message = "There was a problem setting enabled status this @location."
        end
        flash[:notice] = message
      	respond_with(@location)
      end
  
     private

        def sort_column
          Location.column_names.include?(params[:sort]) ? params[:sort] : "name"
        end

        def sort_direction
          %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
        end
  
  
  
  
  end
end