--- 
javascripts: 
- base: 
  - standard
  - standard.ie
  - searchField
  - rails
  - old-browsers
  - mobile
  - list
  - jquery_jgrowl_minimized
  - jquery_fancybox
  - jquery.tip
  - jquery.modal
  - jquery.min
  - jquery
  - jquery.hashchange
  - jquery.dataTables.min
  - jquery.contextMenu
  - jquery.accessibleList
  - jquery-1.4.2.min
  - html5
  - common
  - application
- hud:
  - css_globe_tooltip
  - jquery.colorbox-min
  - fullscreenr
  - hoverintent
  - jquery_lazyload/jquery.lazyload
  - jquery.easing.1.3
  - jquery.innerfade
  - mousewheel
  - jquery-ui-1.5.2
  - hud
  - application
- constellation:
  - html5
  - old-browsers
  - jquery.accessibleList
  - searchField
  - common
  - standard
  - jquery.tip
  - jquery.hashchange
  - jquery.contextMenu
  - jquery.modal
  - list
  - jquery.dataTables.min
  - jquery.datepick/jquery.datepick.min
  - jquery_jgrowl_minimized
  - jquery.blockUI
  - rails
  - forms
  - admin
stylesheets: 
- base: 
  - formtastic
  - formtastic_changes
  - jquery_fancybox
  - jquery_jgrowl
  - popup_packaged
  - silky_buttons
  - yabo-cms
- hud:
  - hud
  - colorbox
  - pagination
  - hs
  - gmaps
- constellation:
  - reset
  - common
  - form
  - standard
  - 960.gs.fluid
  - simple-lists
  - block-lists
  - planning
  - jquery_jgrowl
#  - silky_buttons
  - table
  - calendars
  - wizard
  - gallery
  - yabo-cms
  - gmaps