server_development:
  site_name: 
  site_url: localhost:3000
  company_name: Jujudellago
  admin_email: julien@yabo-concept.ch
  support_name: Jujudellago
  support_email: info@Jujudellago.org
  tagline: testing site
  keywords: ""
  description: ""
#  recaptcha_public_key: 6Lc8XQkAAAAAAKl8HBJfzVcqn9Xf0PmbBEJKy61X   #localhost
#  recaptcha_private_key_key: 6Lc8XQkAAAAAACS5GasqBV_I41s2S7GzVZR_dPtL  #localhost 
  recaptcha_public_key: 6Ldq9AkAAAAAAHcQWpPpX45Ao5003Pzza5x8CrDh  #sangsom
  recaptcha_private_key_key: 6Ldq9AkAAAAAABr0TLGQWJSu1WPLHOK-3Vct-ziN #sangsom
  youtube_api_key: AI39si702hc5ggQ2X14tc1aVOe8IeA6USipeYnHt8tjG6OqK3RluUvdI8CPmbJ1-qgvxGTuqRuzTV4RVFoTZRulIuEn8acSYuw
  
server_test:
  site_name: Jujudellago
  site_url: localhost:3000
  company_name: Jujudellago
  admin_email: julien@yabo-concept.ch
  support_name: Julien Ramel
  support_email: julien@yabo-concept.ch
  tagline: testing site
  keywords: Jujudellago testing site
  description: Designed to test the new Jujudellago platform
server_production:
  site_name: Jujudellago
  site_url: www.Jujudellago.org
  company_name: Jujudellago
  admin_email: info@Jujudellago.org
  support_name: Jujudellago
  support_email: info@Jujudellago.org
  tagline: testing site
  keywords: ""
  description: ""
  recaptcha_public_key: 6LeFZAkAAAAAAIcjIyrDR6ylWsdduSpNNaG6m_Rw
  recaptcha_private_key_key: 6LeFZAkAAAAAACozNtqb1GoznPwk2QFNCFywqLWg
    
    
#   
# Congratulations, julienramel, your application is now registered! Yeah!
#
#     * Your application id is 1kDYNTzV34FbQutu3R0DBy.K75wrDYJWdIBYArGAIongsMaXYk8t0XWpGRXvTdynMjM-
#     * For application entrypoint -> http://Jujudellago.org 
#
# To view your current application ids, click here.
#
# You may want to print this page for your records.
#
# Here's what to do next.
#